In [320]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [321]:
df = pd.read_csv("diabetes.csv")
df.head()

  Pregnancies  Glucose BloodPressure SkinThickness Insulin         BMI
0           6      148            72            35       0        33.6
1           1       85            66            29       0        26.6
2        8\n1  183\n89        64\n66         0\n23   0\n94  23.3\n28.1
3           0      137            40            35     168        43.1
4           5      116            74             0       0        25.6

In [322]:
df.shape

(34, 6)

In [323]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Pregnancies    34 non-null     object
 1   Glucose        34 non-null     object
 2   BloodPressure  34 non-null     object
 3   SkinThickness  34 non-null     object
 4   Insulin        34 non-null     object
 5   BMI            34 non-null     object
dtypes: object(6)
memory usage: 1.7+ KB

In [324]:
df.isnull().sum()

Pregnancies      0
Glucose          0
BloodPressure    0
SkinThickness    0
Insulin          0
BMI              0
dtype: int64

In [325]:
for col in df.columns:
    df[col] = df[col].astype(str).str.split('\n').str[0]

In [326]:
df = df.apply(pd.to_numeric, errors='coerce')
df

    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
0             6      148             72             35        0  33.6
1             1       85             66             29        0  26.6
2             8      183             64              0        0  23.3
3             0      137             40             35      168  43.1
4             5      116             74              0        0  25.6
5             3       78             50             32       88  31.0
6             2      197             70             45      543  30.5
7             8      125             96              0        0   0.0
8             4      110             92              0        0  37.6
9            10      139             80              0        0  27.1
10            1      189             60             23      846  30.1
11            5      166             72             19      175  25.8
12            0      118             84             47      230  45.8
13            7      107             74              0        0  29.6
14            1      103             30             38       83  43.3
15            3      126             88             41      235  39.3
16            8       99             84              0        0  35.4
17            7      196             90              0        0  39.8
18           11      143             94             33      146  36.6
19           10      125             70             26      115  31.1
20            7      147             76              0        0  39.4
21           13      145             82             19      110  22.2
22            5      117             92              0        0  34.1
23            5      109             75             26        0  36.0
24            3       88             58             11       54  24.8
25            6       92             92              0        0  19.9
26           10      122             78             31        0  27.6
27           11      138             76              0        0  33.2
28            9      102             76             37        0  32.9
29            2       90             68             42        0  38.2
30            3      180             64             25       70  34.0
31            7      133             84              0        0  40.2
32            7      106             92             18        0  22.7
33            7      159             64              0        0  27.4

In [327]:
cols = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']

df[cols] = df[cols].replace(0, np.nan)
df

    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI
0             6      148             72           35.0      NaN  33.6
1             1       85             66           29.0      NaN  26.6
2             8      183             64            NaN      NaN  23.3
3             0      137             40           35.0    168.0  43.1
4             5      116             74            NaN      NaN  25.6
5             3       78             50           32.0     88.0  31.0
6             2      197             70           45.0    543.0  30.5
7             8      125             96            NaN      NaN   NaN
8             4      110             92            NaN      NaN  37.6
9            10      139             80            NaN      NaN  27.1
10            1      189             60           23.0    846.0  30.1
11            5      166             72           19.0    175.0  25.8
12            0      118             84           47.0    230.0  45.8
13            7      107             74            NaN      NaN  29.6
14            1      103             30           38.0     83.0  43.3
15            3      126             88           41.0    235.0  39.3
16            8       99             84            NaN      NaN  35.4
17            7      196             90            NaN      NaN  39.8
18           11      143             94           33.0    146.0  36.6
19           10      125             70           26.0    115.0  31.1
20            7      147             76            NaN      NaN  39.4
21           13      145             82           19.0    110.0  22.2
22            5      117             92            NaN      NaN  34.1
23            5      109             75           26.0      NaN  36.0
24            3       88             58           11.0     54.0  24.8
25            6       92             92            NaN      NaN  19.9
26           10      122             78           31.0      NaN  27.6
27           11      138             76            NaN      NaN  33.2
28            9      102             76           37.0      NaN  32.9
29            2       90             68           42.0      NaN  38.2
30            3      180             64           25.0     70.0  34.0
31            7      133             84            NaN      NaN  40.2
32            7      106             92           18.0      NaN  22.7
33            7      159             64            NaN      NaN  27.4

In [328]:
df[cols] = df[cols].fillna(df[cols].mean())
df

    Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin        BMI
0             6      148             72           35.0  220.230769  33.600000
1             1       85             66           29.0  220.230769  26.600000
2             8      183             64           30.6  220.230769  23.300000
3             0      137             40           35.0  168.000000  43.100000
4             5      116             74           30.6  220.230769  25.600000
5             3       78             50           32.0   88.000000  31.000000
6             2      197             70           45.0  543.000000  30.500000
7             8      125             96           30.6  220.230769  32.357576
8             4      110             92           30.6  220.230769  37.600000
9            10      139             80           30.6  220.230769  27.100000
10            1      189             60           23.0  846.000000  30.100000
11            5      166             72           19.0  175.000000  25.800000
12            0      118             84           47.0  230.000000  45.800000
13            7      107             74           30.6  220.230769  29.600000
14            1      103             30           38.0   83.000000  43.300000
15            3      126             88           41.0  235.000000  39.300000
16            8       99             84           30.6  220.230769  35.400000
17            7      196             90           30.6  220.230769  39.800000
18           11      143             94           33.0  146.000000  36.600000
19           10      125             70           26.0  115.000000  31.100000
20            7      147             76           30.6  220.230769  39.400000
21           13      145             82           19.0  110.000000  22.200000
22            5      117             92           30.6  220.230769  34.100000
23            5      109             75           26.0  220.230769  36.000000
24            3       88             58           11.0   54.000000  24.800000
25            6       92             92           30.6  220.230769  19.900000
26           10      122             78           31.0  220.230769  27.600000
27           11      138             76           30.6  220.230769  33.200000
28            9      102             76           37.0  220.230769  32.900000
29            2       90             68           42.0  220.230769  38.200000
30            3      180             64           25.0   70.000000  34.000000
31            7      133             84           30.6  220.230769  40.200000
32            7      106             92           18.0  220.230769  22.700000
33            7      159             64           30.6  220.230769  27.400000

In [329]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Pregnancies    34 non-null     int64
 1   Glucose        34 non-null     int64
 2   BloodPressure  34 non-null     int64
 3   SkinThickness  34 non-null     float64
 4   Insulin        34 non-null     float64
 5   BMI            34 non-null     float64
dtypes: float64(3), int64(3)
memory usage: 1.7 KB

In [330]:
df.head()
df

    Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin        BMI
0             6      148             72           35.0  220.230769  33.600000
1             1       85             66           29.0  220.230769  26.600000
2             8      183             64           30.6  220.230769  23.300000
3             0      137             40           35.0  168.000000  43.100000
4             5      116             74           30.6  220.230769  25.600000
5             3       78             50           32.0   88.000000  31.000000
6             2      197             70           45.0  543.000000  30.500000
7             8      125             96           30.6  220.230769  32.357576
8             4      110             92           30.6  220.230769  37.600000
9            10      139             80           30.6  220.230769  27.100000
10            1      189             60           23.0  846.000000  30.100000
11            5      166             72           19.0  175.000000  25.800000
12            0      118             84           47.0  230.000000  45.800000
13            7      107             74           30.6  220.230769  29.600000
14            1      103             30           38.0   83.000000  43.300000
15            3      126             88           41.0  235.000000  39.300000
16            8       99             84           30.6  220.230769  35.400000
17            7      196             90           30.6  220.230769  39.800000
18           11      143             94           33.0  146.000000  36.600000
19           10      125             70           26.0  115.000000  31.100000
20            7      147             76           30.6  220.230769  39.400000
21           13      145             82           19.0  110.000000  22.200000
22            5      117             92           30.6  220.230769  34.100000
23            5      109             75           26.0  220.230769  36.000000
24            3       88             58           11.0   54.000000  24.800000
25            6       92             92           30.6  220.230769  19.900000
26           10      122             78           31.0  220.230769  27.600000
27           11      138             76           30.6  220.230769  33.200000
28            9      102             76           37.0  220.230769  32.900000
29            2       90             68           42.0  220.230769  38.200000
30            3      180             64           25.0   70.000000  34.000000
31            7      133             84           30.6  220.230769  40.200000
32            7      106             92           18.0  220.230769  22.700000
33            7      159             64           30.6  220.230769  27.400000

In [331]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,f1_score,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [332]:
df['Outcome'] = ((df['Glucose'] > 125) | (df['BMI'] > 30)).astype(int)
X = df.drop('Outcome', axis=1)  
y = df['Outcome']

In [333]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Outcome
0,6,148,72,35.0,220.230769,33.6,1
1,1,85,66,29.0,220.230769,26.6,0
2,8,183,64,30.6,220.230769,23.3,1
3,0,137,40,35.0,168.000000,43.1,1
4,5,116,74,30.6,220.230769,25.6,0

In [334]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [335]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [336]:
models = {
    "Logistic Regression": LogisticRegression(),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "Decision Tree": DecisionTreeClassifier(),
    "SVM (RBF Kernel)": SVC(probability=True)
}

In [337]:
result=[]

In [338]:
for name, model in models.items():
    model.fit(X_train_scaled, y_train)

In [339]:
print("X_train_scaled:", X_train_scaled.shape)
print("y_train:", y_train.shape)
print("X_test_scaled:", X_test_scaled.shape)
print("y_test:", y_test.shape)

X_train_scaled: (27, 6)
y_train: (27,)
X_test_scaled: (7, 6)
y_test: (7,)

In [340]:
results = []
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)

    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='weighted')

    results.append({
        'Model': name,
        'Accuracy': round(acc, 4),
        'F1 Score': round(f1, 4)
    })

In [341]:
results

[{'Model': 'Logistic Regression', 'Accuracy': 0.8571, 'F1 Score': 0.8398},
 {'Model': 'KNN', 'Accuracy': 0.7143, 'F1 Score': 0.5952},
 {'Model': 'Naive Bayes', 'Accuracy': 0.5714, 'F1 Score': 0.5905},
 {'Model': 'Decision Tree', 'Accuracy': 1.0, 'F1 Score': 1.0},
 {'Model': 'SVM (RBF Kernel)', 'Accuracy': 0.7143, 'F1 Score': 0.5952}]

In [1]:
df

NameError: name 'df' is not defined