In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset("titanic")

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [6]:
df.drop([ 'deck', 'embark_town','alive', 'class','who','adult_male'],axis=1, inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [8]:
df["age"].fillna(df["age"].mean(), inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [10]:
df.dropna(subset=["embarked"], inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [12]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()

In [13]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [14]:
df["sex"] = le.fit_transform(df['sex'])
df["embarked"] = le.fit_transform(df['embarked'])

In [15]:
df.head()
df =df.astype(int)

In [16]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [17]:
x= df.drop("survived", axis=1)
y = df["survived"]

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [20]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [21]:
x_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
281       3    1   28      0      0     7         2      1
435       1    0   14      1      2   120         2      0
39        3    0   14      1      0    11         0      0
418       2    1   30      0      0    13         2      1
585       1    0   18      0      2    79         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
433       3    1   17      0      0     7         2      1
807       3    0   18      0      0     7         2      1
25        3    0   38      1      5    31         2      0
85        3    0   33      3      0    15         2      0
10        3    0    4      1      1    16         2      0

[178 rows x 8 columns]

LOGISTIC REGRESION ALGORITHM

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
model =LogisticRegression()

model.fit(x_train,y_train)

LogisticRegression()

In [24]:
y_pred = model.predict(x_test)

In [25]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [26]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

#used confution matrix

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [28]:
accuracy_score(y_test,y_pred)

0.8033707865168539

In [29]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [16, 53]])

In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

KNN ALGORITHAM

In [31]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [32]:
x_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
281       3    1   28      0      0     7         2      1
435       1    0   14      1      2   120         2      0
39        3    0   14      1      0    11         0      0
418       2    1   30      0      0    13         2      1
585       1    0   18      0      2    79         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
433       3    1   17      0      0     7         2      1
807       3    0   18      0      0     7         2      1
25        3    0   38      1      5    31         2      0
85        3    0   33      3      0    15         2      0
10        3    0    4      1      1    16         2      0

[178 rows x 8 columns]

In [33]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [34]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled =scaler.fit_transform(x_test)

In [35]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [37]:
y_pred_knn = knn_model.predict(x_test_scaled)

In [38]:
accuracy_score(y_test,y_pred_knn)

0.7808988764044944

In [39]:
confusion_matrix(y_test,y_pred_knn)

array([[90, 19],
       [20, 49]])

In [40]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.82      0.83      0.82       109
           1       0.72      0.71      0.72        69

    accuracy                           0.78       178
   macro avg       0.77      0.77      0.77       178
weighted avg       0.78      0.78      0.78       178

In [41]:
x_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
281       3    1   28      0      0     7         2      1
435       1    0   14      1      2   120         2      0
39        3    0   14      1      0    11         0      0
418       2    1   30      0      0    13         2      1
585       1    0   18      0      2    79         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
433       3    1   17      0      0     7         2      1
807       3    0   18      0      0     7         2      1
25        3    0   38      1      5    31         2      0
85        3    0   33      3      0    15         2      0
10        3    0    4      1      1    16         2      0

[178 rows x 8 columns]

In [42]:
from sklearn.naive_bayes import GaussianNB

In [43]:
model_NB = GaussianNB()

In [44]:
model_NB.fit(x_train,y_train)

GaussianNB()

In [45]:
y_pred_NB = model_NB.predict(x_test)

In [46]:
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [47]:
accuracy_score(y_test,y_pred_NB)

0.7752808988764045

In [48]:
confusion_matrix(y_test,y_pred_NB)

array([[84, 25],
       [15, 54]])

#Desion Tree

In [49]:
from sklearn.tree import DecisionTreeClassifier

In [50]:
model_DT = DecisionTreeClassifier(random_state=42)

In [51]:
model_DT.fit(x_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [52]:
y_pred_DT = model_DT.predict(x_test_scaled)

In [53]:
accuracy_score(y_test,y_pred_DT)

0.7696629213483146

In [54]:
confusion_matrix(y_test,y_pred_DT)

array([[88, 21],
       [20, 49]])

In [55]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81       109
           1       0.70      0.71      0.71        69

    accuracy                           0.77       178
   macro avg       0.76      0.76      0.76       178
weighted avg       0.77      0.77      0.77       178

In [56]:
y_pred_DT

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0])

SVM(supoort vector mashine)

In [57]:
from sklearn.svm import SVC

In [58]:
model_svm = SVC(kernel = 'rbf')

In [59]:
model_svm.fit(x_train_scaled,y_train)

SVC()

In [60]:
y_pred_svm = model_svm. predict(x_test_scaled)

In [61]:
accuracy_score(y_test,y_pred_svm)

0.8258426966292135

In [62]:
confusion_matrix(y_test,y_pred_svm)

array([[96, 13],
       [18, 51]])

In [63]:

print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       109
           1       0.80      0.74      0.77        69

    accuracy                           0.83       178
   macro avg       0.82      0.81      0.81       178
weighted avg       0.82      0.83      0.82       178

CROSS VALIDATION

In [64]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [65]:
x = df.drop('survived',axis= 1)
y= df['survived']

In [66]:
from sklearn.model_selection import cross_val_score

In [71]:
scaler = StandardScaler()
x_scal = scaler.fit_transform(x)

In [72]:
scores = cross_val_score(model_svm,x_scal,y,cv = 5,scoring= 'accuracy')

In [73]:
print(scores)

[0.83146067 0.82022472 0.81460674 0.80898876 0.86440678]

In [74]:
print(scores.mean())

0.8279375357074844

In [75]:
scores = cross_val_score(knn_model,x_scal,y,cv = 5,scoring= 'accuracy')

In [76]:
print(scores)

[0.78651685 0.76404494 0.8258427  0.81460674 0.80225989]

In [77]:
print(scores.mean())

0.7986542245921411